[workspace]
channels = ["conda-forge"]
name = "f360-to-b123d"
platforms = ["win-64"]
version = "0.0.0"
preview = ["pixi-build"]

[package] 
name = "f360-to-b123d"
version = "1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "*" }
source.path = "./"

[dependencies]
build123d = ">=0.9.0, <1"

[feature.test.pypi-dependencies]
ocp-vscode = "*"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest"

[environments]
test = { features = ["test"], solve-group = "default" }

